const GET_ALL_USERS = 'users/GET_ALL_USERS'
const CREATE_NEW_USER = 'users/CREATE_NEW_USER'
const CREATE_NEW_USER_ERRED = 'users/CREATE_NEW_USER_ERRED'
const CLEAR_ERROR = 'users/CLEAR_ERROR'

export default {
    GET_ALL_USERS,
    CREATE_NEW_USER,
    CREATE_NEW_USER_ERRED,
    CLEAR_ERROR
}