const GET_ALL_USERS = 'users/GET_ALL_USERS'
const CREATE_NEW_USER = 'users/CREATE_NEW_USER'
const CREATE_NEW_USER_ERRER = 'users/CREATE_NEW_USER_ERRER'

export default {
    GET_ALL_USERS,
    CREATE_NEW_USER,
    CREATE_NEW_USER_ERRER
}