const GET_ALL_USERS = 'users/GET_ALL_USERS'
const TOGGLE_CREATE_NEW_USER = 'users/TOGGLE_CREATE_NEW_USER'
const CREATE_NEW_USER = 'users/CREATE_NEW_USER'
const CREATE_NEW_USER_ERRED = 'users/CREATE_NEW_USER_ERRED'
const CLEAR_ERROR = 'users/CLEAR_ERROR'
const TOGGLE_DELETE_USER = 'users/TOGGLE_DELETE_USER'
const DELETE_USER_SUCCESS = 'users/DELETE_USER_SUCCESS'

export default {
    GET_ALL_USERS,
    TOGGLE_CREATE_NEW_USER,
    CREATE_NEW_USER,
    CREATE_NEW_USER_ERRED,
    CLEAR_ERROR,
    TOGGLE_DELETE_USER,
    DELETE_USER_SUCCESS
}